# Use this to skip checks that incur high costs or break Free Tier eligibility
skip-check:
  # Cloudfront-specific skips
  - CKV_AWS_86 # Ensure CloudFront distribution has Access Logging enabled (Avoids S3 Put/Storage costs.)
  - CKV_AWS_68 # CloudFront Distribution should have WAF enabled (Avoids ~$25/month + request fees.)
  - CKV_AWS_310 # Ensure CloudFront distributions should have origin failover configured (Requires a second S3 bucket in a different region (adds complexity/cost))
  - CKV2_AWS_47 # Ensure AWS CloudFront attached WAFv2 WebACL is configured with AMR for Log4j Vulnerability (Avoids costs ~$25/month)
  - CKV2_AWS_42 # Ensure AWS CloudFront distribution uses custom SSL certificate (Avoids domain cost)
  - CKV2_AWS_32 # Ensure CloudFront distribution has a response headers policy attached (Not required for a static resume)
  - CKV_AWS_174 # Verify CloudFront Distribution Viewer Certificate is using TLS v1.2 or higher (Avoid domain cost)
  - CKV_AWS_374 # Ensure AWS CloudFront web distribution has geo restriction enabled (Intended for global access)

  # API-Gateway-specific skips
  - CKV_AWS_76 # Ensure API Gateway has Access Logging enabled (Avoids CloudWatch ingestion costs)
  - CKV_AWS_309 # Ensure API GatewayV2 routes specify an authorization type (Not necessary, replaced with IAM)

  # Database-specific skips
  - CKV_AWS_28 # Ensure DynamoDB point in time recovery (backup) is enabled (Avoids ~$0.20 per GB / month.)
  - CKV_AWS_119  # Ensure DynamoDB Tables are encrypted using a KMS Customer Managed CMK (Avoids $1/month per key)

  # lambda-specific skips
  - CKV_AWS_117 # Ensure that AWS Lambda function is configured inside a VPC (Avoids ~$32/month (NAT Gateway))
  - CKV_AWS_116 # Ensure that AWS Lambda function is configured for a Dead Letter Queue(DLQ) (Skip to avoid SQS costs)
  - CKV_AWS_115 # Ensure that AWS Lambda function is configured for function-level concurrent execution limit (Not relevant due to cost)
  - CKV_AWS_272 # Ensure AWS Lambda function is configured to validate code-signing (Complex setup, unnecessary for small projects)
  - CKV_AWS_173 # Check encryption settings for Lambda environmental variable (Avoids $1/mo KMS fee)

  # S3-specific skips
  - CKV_AWS_145 # Ensure that S3 buckets are encrypted with KMS by default (Avoids $1/mo KMS fee)
  - CKV_AWS_18  # Ensure the S3 bucket has access logging enabled (Saves on request/storage costs)
  - CKV2_AWS_62 # Ensure S3 buckets should have event notifications enabled (Irrelevant)
  - CKV_AWS_144 # Ensure that S3 bucket has cross-region replication enabled (Prevents doubling storage costs)

  # GitHub Action skips
  - CKV2_GHA_1 # Ensure top-level permissions are not set to write-all (Intentional skip as the workflows requires the permission)
